### ISSUE TITLE
Maybe a bug in sc_wave_features_mod_8?

### ISSUE THREAD

**Issue by jiumao2** [open-ephys/simpleclust#13]
sc_wave_features_wc_mod_8.m 
```
scales=24;
inputs=8;   % how many features to compute, ~10 make sense

% CALCULATES FEATURES

cc=zeros(nspk,ls);
for i=1:nspk                                % Wavelet decomposition
    [c,l]=wavedec(spikes(i,:),scales,'haar');
    cc(i,1:ls)=c(1:ls);
end
```

I don't know why you chose scales = 24. My 'wavedec' function made variable c 1x82 vector where 2nd to 19th elements were all zeros. It is because the scales is too big for wavelet transform of a 64-sample spike waveform.

I think we should change the scales to 6 or write 'cc(i,1:ls)=c(end-ls+1:end)' rather than 'cc(i,1:ls)=c(1:ls)'?

**Comment by jvoigts** [comment]
That sounds reasonable - I ended up not using these features so its very likely that the hardcoded numbers only work on some test cases.  If you can get this working for you, just put in a PR. Thx!

**Comment by jiumao2** [comment]
That's fine. Thank you for your reply!

**Comment by jvoigts** [comment]
should be fixed now in https://github.com/open-ephys/simpleclust/pull/14#issue-1072974623
